<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OnlinePaymentts_Migrado/CON_EAPLOGS/BS_PRC_WS_ES_VALIDO" name="BS_PRC_WS_ES_VALIDO-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="JCA_PRC_WS_ES_VALIDO.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OnlinePaymentts_Migrado/CON_EAPLOGS/BS_PRC_WS_ES_VALIDO"/>
    <wsdl:binding name="BS_PRC_WS_ES_VALIDO_ptt-binding" type="bs:BS_PRC_WS_ES_VALIDO_ptt" xmlns:bs="http://xmlns.oracle.com/pcbpel/adapter/db/OnlinePaymentts_Migrado/CON_EAPLOGS/BS_PRC_WS_ES_VALIDO">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="BS_PRC_WS_ES_VALIDO">
            <soap:operation soapAction="BS_PRC_WS_ES_VALIDO"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>